config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#login'
  get 'signup', to: 'users#new'
  get 'login' , to: 'static_pages#login'
  post 'login', to: 'static_pages#create'
  delete 'logout', to: 'static_pages#destroy'
  
  resources :users
  resources :animals
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }

    belongs_to :animal_type_id
    belongs_to :user
end

app/models/animal_type.rb
class AnimalType < ActiveRecord::Base
    has_many :animals
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  # validates :age, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 120}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                     format: { with: VALID_EMAIL_REGEX },
                     uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :animals
  belongs_to :user
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update, :new]
  before_action :set_animal, only: [:show, :edit, :destroy, :update]
  
  def index
    @animals = Animal.all
  end
  
  def edit
  end  
  
  def show
  end
  
  def new
    @animal = Animal.new
  end
  
  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to animals_path
    else
      render 'new'
    end
  end
  
  def destroy
    @animal.destroy
    redirect_to animals_path
  end
  
  def update
    if @animal.update(animal_params)
      redirect_to animal_path
    else
      render 'edit'
    end
  end
  
  private
  def animal_params
    params.require(:animal).permit(:name, :age, :sex, :breed, :animal_type_id, :chronic_illness)
  end
  
  def set_animal
     @animal = Animal.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include StaticPagesHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
    def home
    @animal_type = current_user.animal_types.build if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update, :new]
  before_action :set_user, only: [:show, :edit, :update]
  
  def index
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(params[:user_id])
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :age, :sex, :password,
                                 :password_confirmation)
  end
  
  def set_user
     @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@animal) do |f| %>

      <%= f.label :名前 %>
      <%= f.text_field :name %>

      <%= f.label :年齢 %>
      <%= f.text_field :age %>

      <%= f.label :性別 %>
      <%= f.text_field :sex %>
      
      <%= f.label :種類 %>
      <%= f.text_field :breed %>

      <%= f.label :感染症 %>
      <%= f.text_field :chronic_illness %>
      
      動物種
      <%= f.collection_select:animal_type_id,AnimalType.all,:id,:name %>
      
      <%# options = ["犬", "猫", "爬虫類", "鳥類", "小動物", "その他"] %>
      <%#= f.select :animal_type_id, options %>

      <%#= f.label :通院 %>
      <%#= f.text_field :attend_the_hospital %>

      <%#= f.label :ワクチン %>
      <%#= f.text_field :vaccine %>

      <%#= f.label :血液検査 %>
      <%#= f.text_field :blood_test %>

      <%= f.submit "Create animal", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<!--血液検査、ワクチン、通院、動物種、アイコン　-->

app/views/animals/edit.html.erb
<h1><%= @animal.name %></h1>

<%= render 'form' %>

app/views/animals/index.html.erb
<div class="table-responsive">
  <!-- テーブルにクラスを追加 -->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @animals.each do |animal| %>
        <tr>
          <td><%= animal.name %></td>
          <td><%= link_to 'Show', animal %></td>
          <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
          <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/animals/new.html.erb
<h1>カルテ新規作成</h1>

<%= render 'form' %>

app/views/animals/show.html.erb
<%= form_for @animal do |f| %>

  <div class="row">
  <aside class="col-md-4">
      <h1>
        <%= @animal.name %>
      </h1>
　　　　
　　　　<div class="form-horizontal" role="form" style="clear:left;">
         <div class="form-group">
           <%= f.label :性別, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :sex, :readonly => true, :class => "form-control" %>
            </div>
         </div>

         <div class="form-group">
           <%= f.label :年齢, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :age, :readonly => true, :class => "form-control" %>
           </div>
         </div>

         <div class="form-group">
           <%= f.label :種類, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :breed, :readonly => true, :class => "form-control" %>
           </div>
         </div>
         
         <div class="form-group">
           <%= f.label :感染症, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :chronic_illness, :readonly => true, :class => "form-control" %>
           </div>
         </div>
         
          <div class="form-group">
           <%= f.label :動物種, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :animal_type_id, :readonly => true, :class => "form-control" %>
           </div>
         </div>
<% end %>

</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Breed-animals", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "ホーム",  users_path %></li>
        　<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
            </ul>
          </li>
        　<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              動物 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "動物一覧", animals_path %></li>
              <li><%= link_to "カルテ新規作成", new_animal_path %></li>
            </ul>
          </li>
        <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breed Animals</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/static_pages/login.html.erb
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>edit_user</h1>

app/views/users/index.html.erb
<h1>ホーム</h1>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= form_for @user do |f| %>

  <div class="row">
  <aside class="col-md-4">
      <h1>
        <%= @user.name %>
      </h1>
　　　　
　　　　<div class="form-horizontal" role="form" style="clear:left;">
         <div class="form-group">
           <%= f.label :性別, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :sex, :readonly => true, :class => "form-control" %>
            </div>
         </div>

         <div class="form-group">
           <%= f.label :メールアドレス, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :email, :readonly => true, :class => "form-control" %>
           </div>
         </div>

         <div class="form-group">
           <%= f.label :年齢, :class => "col-sm-3 countrol-label" %>
           <div class="col-sm-7">
             <%= f.text_field :age, :readonly => true, :class => "form-control" %>
           </div>
         </div>
<% end %>

</div>